W4D4/skeleton 4/config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :cats, except: :destroy
  resources :cat_rental_requests, only: [:new, :create] do
    post 'approve', on: :member
    post 'deny', on: :member
  end

  resources :users, only: [:create,:new]
  resource :session, only: [:create,:new,:destroy]


  root to: redirect('/cats')
end

W4D4/skeleton 4/app/models/cat.rb
require 'action_view'

class Cat < ApplicationRecord
  include ActionView::Helpers::DateHelper

  # freeze ensures that constants are immutable
  CAT_COLORS = %w(black white orange brown).freeze

  validates :birth_date, :color, :name, :sex, presence: true
  validates :color, inclusion: CAT_COLORS
  validates :sex, inclusion: %w(M F)

  has_many :rental_requests,
    class_name: :CatRentalRequest,
    dependent: :destroy

  belongs_to :owner,
  primary_key: :id,
  foreign_key: :user_id,
  class_name: 'User'




  def age
    time_ago_in_words(birth_date)
  end
end

W4D4/skeleton 4/app/controllers/cats_controller.rb
class CatsController < ApplicationController
  before_action :ensure_owns_cat, only: [:edit,:update]

  def index
    @cats = Cat.all
    render :index
  end

  def show
    @cat = Cat.find(params[:id])
    render :show
  end

  def new
    @cat = Cat.new
    render :new
  end



  def create
    @cat = Cat.new(cat_params)
    if @cat.save
      redirect_to cat_url(@cat)
    else
      flash.now[:errors] = @cat.errors.full_messages
      render :new
    end
  end

  def edit
    @cat = Cat.find(params[:id])
    # current_user.cats.select(id: params[:id])
    render :edit
  end

  def update
    @cat = Cat.find(params[:id])
    if @cat.update_attributes(cat_params)
      redirect_to cat_url(@cat)
    else
      flash.now[:errors] = @cat.errors.full_messages
      render :edit
    end
  end

  private

  def cat_params
    params.require(:cat).permit(:age, :birth_date, :color, :description, :name, :sex, :user_id)
  end
end

W4D4/skeleton 4/app/helpers/cats_helper.rb
module CatsHelper
end

W4D4/skeleton 4/app/views/cats/_form.html.erb
<% action = (cat.persisted? ? cat_url(cat) : cats_url) %>
<% method = (cat.persisted? ? :patch : :post) %>

<form action="<%= action %>" method="post">
  <input type="hidden"
        name="authenticity_token"
        value="<%= form_authenticity_token %>">
  <input type="hidden" name="_method" value="<%= method %>">

  <label for="cat_name">Name</label>
  <input
    type="text"
    name="cat[name]"
    id="cat_name"
    value="<%= cat.name %>">

  <label for="cat_birth_date">Birth date</label>
  <input
    type="date"
    name="cat[birth_date]"
    id="cat_birth_date"
    value="<%= cat.birth_date %>">
  <br>

  <label for="cat_color">Color</label>
  <select name="cat[color]" id="cat_color">
    <option></option>
    <% Cat::CAT_COLORS.each do |color| %>
      <option
        <%= cat.color == color ? "selected" : "" %>
        value="<%= color %>">
        <%= color.upcase %>
      </option>
    <% end %>
  </select>
  <br>

  <input
    type="radio"
    name="cat[sex]"
    value="M"
    id="cat_sex_male"
    <%= cat.sex == "M" ? "checked" : "" %>>
  <label for="cat_sex_male">Male</label>
  <input
    type="radio"
    name="cat[sex]"
    value="F"
    id="cat_sex_female"
    <%= cat.sex == "F" ? "checked" : "" %>>
  <label for="cat_sex_female">Female</label>
  <br>

  <label>
    Description
    <textarea name="cat[description]"><%= cat.description %></textarea>
  </label>

  <input name="cat[user_id]" type="hidden" value="<%= current_user.id %>">

  <% submit_text = (cat.persisted? ? 'Update' : 'Create') + ' cat!' %>
  <input type="submit" value="<%= submit_text %>">
</form>

W4D4/skeleton 4/app/views/cats/_req_tr.html.erb
<tr>
  <td><%= req.start_date %></td>
  <td><%= req.end_date %></td>
  <td><%= req.user.username %> </td>
  <td>
    <% if req.pending? %>
      <form action="<%= approve_cat_rental_request_url(req) %>" method="POST">
        <input type="hidden"
              name="authenticity_token"
              value="<%= form_authenticity_token %>">
        <input type="submit" value="Approve" />
      </form>
      <form action="<%= deny_cat_rental_request_url(req) %>" method="POST">
        <form action="<%=new_cat_rental_request_url %>" method="GET">
          <input type="hidden"
                name="authenticity_token"
                value="<%= form_authenticity_token %>">
        <input type="submit" value="Deny" />
      </form>
    <% else %>
      <%= req.status %>
    <% end %>
  </td>
</tr>

W4D4/skeleton 4/app/views/cats/edit.html.erb
<h1>Edit My Cat</h1>
<%= render 'shared/errors' %>
<%= render 'form', cat: @cat %>

W4D4/skeleton 4/app/views/cats/index.html.erb
<h1>Cats upon cats!</h1>

<ul>
  <% @cats.each do |cat| %>
    <li><a href="<%= cat_url(cat) %>"><%= cat.name %></a></li>
  <% end %>
</ul>


<ul>
  <li>
    <form action="<%= session_url %>" method="POST">
      <input type="hidden"
             name="authenticity_token"
             value="<%= form_authenticity_token %>">
      <input type="hidden" value="delete" name="_method" />
      <input type="submit" value="Logout" />
    </form>
  </li>
</ul>
<a href="<%= new_cat_url %>">Create cat</a>

W4D4/skeleton 4/app/views/cats/new.html.erb
<h1>New Cat</h1>

<%= render 'shared/errors' %>
<%= render 'form', cat: @cat %>

W4D4/skeleton 4/app/views/cats/show.html.erb
<h1><%= @cat.name %></h1>
<style>

* {
  background-color: #eee;
  color: red;
  
}

</style>

<table>
  <tr>
    <th>Attribute</th>
    <th>Value</th>
  </tr>
  <% [:age, :birth_date, :color, :sex].each do |attr_name| %>
    <tr>
      <td><%= attr_name %></td>
      <td><%= @cat.send(attr_name) %></td>
    </tr>
  <% end %>
</table>

<%= link_to "Edit #{@cat.name}", edit_cat_url(@cat) %>
<form action="<%=new_cat_rental_request_url %>" method="GET">
  <input type="hidden"
        name="authenticity_token"
        value="<%= form_authenticity_token %>">
  <input type="submit" value="Rent a Hella Cute Cat" />
</form>

<h2>Rental Requests</h2>
<table>
  <tr>
    <th>Start Date</th>
    <th>End Date</th>
    <th>Renter</th>
    <th>Status</th>
  </tr>
  <% @cat.rental_requests.order('start_date').each do |req| %>
    <%= render 'req_tr', req: req %>
  <% end %>
</table>